In [1]:
import pandas as pd
import numpy as np

In [2]:
# Pandas Version
pd.__version__

'2.2.2'

In [3]:
# data loading
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
# Records Count
len(df)

10000

In [5]:
# Fuel Types
df['fuel_type'].nunique()
df['fuel_type'].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [6]:
# missing values
missing = df.isnull().sum()
missing[missing > 0]
(missing > 0).sum()

2

In [7]:
# Maximum Fuel Efficiency for Asian Cars
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

41.2

In [8]:
# Finding median value of horsepower
median_before = df['horsepower'].median()
median_before

254.0

In [9]:
most_frequent = df['horsepower'].mode()[0]
most_frequent

252.0

In [10]:
df['horsepower'] = df['horsepower'].fillna(most_frequent)

In [11]:
median_after = df['horsepower'].median()
median_after

252.0

In [12]:
print(f'Before: {median_before}, After: {median_after}')
if median_after > median_before:
    print('Yes, it increased')
elif median_after < median_before:
    print('Yes, it decreased')
else:
    print('No')

Before: 254.0, After: 252.0
Yes, it decreased

In [13]:
# Sum of Weight of Cars from Asia
asia = df[df['origin'] == 'Asia']
subset = asia[['vehicle_weight', 'model_year']].head(7)
subset

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [14]:
X = subset.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]], dtype=int64)

In [15]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]], dtype=int64)

In [16]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [17]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [18]:
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [19]:
w.sum()

0.36919696904925486